"""update human consistency constraints

Revision ID: 06b0076550c6
Revises: b44a4f95a9e7
Create Date: 2026-02-26 13:07:52.812282

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06b0076550c6'
down_revision: Union[str, Sequence[str], None] = 'b44a4f95a9e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_conversations_human_status'), table_name='conversations')
    op.create_index('ix_conversations_human_queue', 'conversations', ['business_id', 'human_status', 'started_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_conversations_human_queue', table_name='conversations')
    op.create_index(op.f('ix_conversations_human_status'), 'conversations', ['human_status'], unique=False)
    # ### end Alembic commands ###
