"""initial schema

Revision ID: 0930cb0695fa
Revises: 
Create Date: 2026-02-24 15:31:13.429726

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0930cb0695fa'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('code', sa.String(length=60), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price_monthly', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('message_quota', sa.Integer(), nullable=False),
    sa.Column('features', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('message_quota >= 0', name='ck_plans_message_quota_non_negative'),
    sa.CheckConstraint('price_monthly >= 0', name='ck_plans_price_monthly_non_negative'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uq_plans_code'),
    sa.UniqueConstraint('name', name='uq_plans_name')
    )
    op.create_index('ix_plans_code', 'plans', ['code'], unique=False)
    op.create_table('businesses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('slug', sa.String(length=160), nullable=False),
    sa.Column('industry', sa.String(length=80), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('whatsapp_number', sa.String(length=40), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status in ('active', 'inactive', 'suspended')", name='ck_businesses_status'),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug', name='uq_businesses_slug')
    )
    op.create_index('ix_businesses_plan_id', 'businesses', ['plan_id'], unique=False)
    op.create_index('ix_businesses_status', 'businesses', ['status'], unique=False)
    op.create_table('agents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('capabilities', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role in ('agent', 'admin', 'supervisor')", name='ck_agents_role'),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'email', name='uq_agents_business_email')
    )
    op.create_index('ix_agents_business_id', 'agents', ['business_id'], unique=False)
    op.create_index('ix_agents_is_active', 'agents', ['is_active'], unique=False)
    op.create_table('business_configs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.Column('handoff_enabled', sa.Boolean(), nullable=False),
    sa.Column('assisted_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('autonomous_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("mode in ('assisted', 'autonomous')", name='ck_business_configs_mode'),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', name='uq_business_configs_business_id')
    )
    op.create_index('ix_business_configs_mode', 'business_configs', ['mode'], unique=False)
    op.create_table('business_usages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('metric', sa.String(length=40), nullable=False),
    sa.Column('used_count', sa.Integer(), nullable=False),
    sa.Column('limit_count', sa.Integer(), nullable=True),
    sa.Column('usage_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('limit_count is null or limit_count >= 0', name='ck_business_usages_limit_count_non_negative'),
    sa.CheckConstraint('period_end >= period_start', name='ck_business_usages_period_order'),
    sa.CheckConstraint('used_count >= 0', name='ck_business_usages_used_count_non_negative'),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'period_start', 'period_end', 'metric', name='uq_business_usages_period_metric')
    )
    op.create_index('ix_business_usages_business_id', 'business_usages', ['business_id'], unique=False)
    op.create_index('ix_business_usages_metric', 'business_usages', ['metric'], unique=False)
    op.create_table('items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('external_id', sa.String(length=120), nullable=True),
    sa.Column('name', sa.String(length=180), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('item_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("type in ('product', 'service', 'reservation', 'appointment', 'meeting', 'generic')", name='ck_items_type'),
    sa.CheckConstraint('price >= 0', name='ck_items_price_non_negative'),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'external_id', name='uq_items_business_external_id')
    )
    op.create_index('ix_items_business_id', 'items', ['business_id'], unique=False)
    op.create_index('ix_items_is_active', 'items', ['is_active'], unique=False)
    op.create_index('ix_items_type', 'items', ['type'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('external_id', sa.String(length=128), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('name', sa.String(length=160), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('locale', sa.String(length=12), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('profile', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'external_id', name='uq_users_business_external_id')
    )
    op.create_index('ix_users_business_id', 'users', ['business_id'], unique=False)
    op.create_index('ix_users_phone', 'users', ['phone'], unique=False)
    op.create_table('conversations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('assigned_agent_id', sa.UUID(), nullable=True),
    sa.Column('channel', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.Column('control_mode', sa.String(length=20), nullable=False),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('started_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_message_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('closed_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("control_mode in ('ai', 'human')", name='ck_conversations_control_mode'),
    sa.CheckConstraint("mode in ('assisted', 'autonomous')", name='ck_conversations_mode'),
    sa.CheckConstraint("status in ('active', 'closed', 'archived')", name='ck_conversations_status'),
    sa.ForeignKeyConstraint(['assigned_agent_id'], ['agents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_conversations_business_id', 'conversations', ['business_id'], unique=False)
    op.create_index('ix_conversations_last_message_at', 'conversations', ['last_message_at'], unique=False)
    op.create_index('ix_conversations_user_id', 'conversations', ['user_id'], unique=False)
    op.create_index('uq_conversations_active_user', 'conversations', ['business_id', 'user_id'], unique=True, postgresql_where=sa.text("status = 'active'"))
    op.create_table('user_usages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('metric', sa.String(length=40), nullable=False),
    sa.Column('used_count', sa.Integer(), nullable=False),
    sa.Column('limit_count', sa.Integer(), nullable=True),
    sa.Column('usage_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('limit_count is null or limit_count >= 0', name='ck_user_usages_limit_count_non_negative'),
    sa.CheckConstraint('period_end >= period_start', name='ck_user_usages_period_order'),
    sa.CheckConstraint('used_count >= 0', name='ck_user_usages_used_count_non_negative'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'period_start', 'period_end', 'metric', name='uq_user_usages_period_metric')
    )
    op.create_index('ix_user_usages_metric', 'user_usages', ['metric'], unique=False)
    op.create_index('ix_user_usages_user_id', 'user_usages', ['user_id'], unique=False)
    op.create_table('conversation_transfers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('from_agent_id', sa.UUID(), nullable=True),
    sa.Column('to_agent_id', sa.UUID(), nullable=True),
    sa.Column('from_mode', sa.String(length=20), nullable=False),
    sa.Column('to_mode', sa.String(length=20), nullable=False),
    sa.Column('requested_by', sa.String(length=64), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('transfer_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('requested_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.CheckConstraint("from_mode in ('ai', 'human')", name='ck_conversation_transfers_from_mode'),
    sa.CheckConstraint("status in ('pending', 'accepted', 'rejected', 'cancelled')", name='ck_conversation_transfers_status'),
    sa.CheckConstraint("to_mode in ('ai', 'human')", name='ck_conversation_transfers_to_mode'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['from_agent_id'], ['agents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['to_agent_id'], ['agents.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_conversation_transfers_conversation_id', 'conversation_transfers', ['conversation_id'], unique=False)
    op.create_index('ix_conversation_transfers_status', 'conversation_transfers', ['status'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('agent_id', sa.UUID(), nullable=True),
    sa.Column('sender_type', sa.String(length=20), nullable=False),
    sa.Column('direction', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('content_type', sa.String(length=32), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("direction in ('inbound', 'outbound', 'internal')", name='ck_messages_direction'),
    sa.CheckConstraint("sender_type in ('user', 'agent', 'assistant', 'system')", name='ck_messages_sender_type'),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_messages_conversation_created_at', 'messages', ['conversation_id', 'created_at'], unique=False)
    op.create_index('ix_messages_conversation_id', 'messages', ['conversation_id'], unique=False)
    op.create_index('ix_messages_created_at', 'messages', ['created_at'], unique=False)
    op.create_table('requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=True),
    sa.Column('item_id', sa.UUID(), nullable=True),
    sa.Column('validated_by_agent_id', sa.UUID(), nullable=True),
    sa.Column('type', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('scheduled_for', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('human_validation_required', sa.Boolean(), nullable=False),
    sa.Column('request_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('validated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status in ('pending', 'confirmed', 'cancelled', 'completed', 'rejected')", name='ck_requests_status'),
    sa.CheckConstraint('char_length(type) > 0', name='ck_requests_type_not_empty'),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['validated_by_agent_id'], ['agents.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_requests_business_id', 'requests', ['business_id'], unique=False)
    op.create_index('ix_requests_scheduled_for', 'requests', ['scheduled_for'], unique=False)
    op.create_index('ix_requests_status', 'requests', ['status'], unique=False)
    op.create_index('ix_requests_user_id', 'requests', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_requests_user_id', table_name='requests')
    op.drop_index('ix_requests_status', table_name='requests')
    op.drop_index('ix_requests_scheduled_for', table_name='requests')
    op.drop_index('ix_requests_business_id', table_name='requests')
    op.drop_table('requests')
    op.drop_index('ix_messages_created_at', table_name='messages')
    op.drop_index('ix_messages_conversation_id', table_name='messages')
    op.drop_index('ix_messages_conversation_created_at', table_name='messages')
    op.drop_table('messages')
    op.drop_index('ix_conversation_transfers_status', table_name='conversation_transfers')
    op.drop_index('ix_conversation_transfers_conversation_id', table_name='conversation_transfers')
    op.drop_table('conversation_transfers')
    op.drop_index('ix_user_usages_user_id', table_name='user_usages')
    op.drop_index('ix_user_usages_metric', table_name='user_usages')
    op.drop_table('user_usages')
    op.drop_index('uq_conversations_active_user', table_name='conversations', postgresql_where=sa.text("status = 'active'"))
    op.drop_index('ix_conversations_user_id', table_name='conversations')
    op.drop_index('ix_conversations_last_message_at', table_name='conversations')
    op.drop_index('ix_conversations_business_id', table_name='conversations')
    op.drop_table('conversations')
    op.drop_index('ix_users_phone', table_name='users')
    op.drop_index('ix_users_business_id', table_name='users')
    op.drop_table('users')
    op.drop_index('ix_items_type', table_name='items')
    op.drop_index('ix_items_is_active', table_name='items')
    op.drop_index('ix_items_business_id', table_name='items')
    op.drop_table('items')
    op.drop_index('ix_business_usages_metric', table_name='business_usages')
    op.drop_index('ix_business_usages_business_id', table_name='business_usages')
    op.drop_table('business_usages')
    op.drop_index('ix_business_configs_mode', table_name='business_configs')
    op.drop_table('business_configs')
    op.drop_index('ix_agents_is_active', table_name='agents')
    op.drop_index('ix_agents_business_id', table_name='agents')
    op.drop_table('agents')
    op.drop_index('ix_businesses_status', table_name='businesses')
    op.drop_index('ix_businesses_plan_id', table_name='businesses')
    op.drop_table('businesses')
    op.drop_index('ix_plans_code', table_name='plans')
    op.drop_table('plans')
    # ### end Alembic commands ###
